# Generated by Django 4.2.5 on 2023-10-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almasy', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='sharePost',
        ),
    ]
