# Generated by Django 4.2.5 on 2023-11-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almasy', '0003_rename_post_sharepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sharePost',
            new_name='Share',
        ),
    ]
