# Generated by Django 4.2.5 on 2023-12-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almasy', '0004_rename_sharepost_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='likes',
        ),
    ]
