# Generated by Django 4.2.5 on 2023-12-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almasy', '0006_sharedphotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedPhotos',
            new_name='SharedPhoto',
        ),
    ]
