# Generated by Django 4.2.5 on 2023-12-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almasy', '0008_alter_sharedphoto_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedPhoto',
        ),
    ]
